zabbix_repo_base_url: "https://repo.zabbix.com/zabbix"
ubuntu_version: "{{ ansible_distribution_version }}"


zabbix_repo_url: "{{ zabbix_repo_base_url }}/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/"

zabbix_repo_package: "zabbix-release_latest+ubuntu{{ ubuntu_version }}_all.deb"
zabbix_repo_package_full_url: "{{ zabbix_repo_url }}{{ zabbix_repo_package }}"




temp_dir: "/tmp"
zabbix_repo_package_local_path: "{{ temp_dir }}/{{ zabbix_repo_package }}"

schema_file_path: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
mysql_socket: /var/run/mysqld/mysqld.sock
zabbix_config_file: /etc/zabbix/zabbix_server.conf
mysql_data_dir: /var/lib/mysql
