zabbix_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ansible_facts['distribution_version'] }}_all.deb"
zabbix_release_file: "zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ansible_facts['distribution_version'] }}_all.deb"
zabbix_packages:
  - zabbix-agent2
  - zabbix-agent2-plugin-*
zabbix_agent_config_path: "/etc/zabbix/zabbix_agent2.conf"

# https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb
# dpkg -i zabbix-release_latest_7.0+ubuntu24.04_all.deb